version: "3"
services:
    frontend:
        image: aybims/hngstage2:frontend
        container_name: frontend
        ports:
          - 3000:3000
        depends_on:
          - backend
    backend:
        image: aybims/hngstage2:api
        container_name: api
        ports:
            - 8000:8000